properties
#Application
spring.application.name = backend

#SQL server connection
#DESKTOP-9LP4BR7\SQLEXPRESS
spring.datasource.url = jdbc:sqlserver://localhost;databaseName=ContactManagementDB;ecrypt=true;trustServerCertificate=true

spring.datasource.username =
spring.datasource.password =

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


#JPA / Hibernate

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql = true


#Server Port
server.port = 8080